fmod PATH is
protecting NAT .
protecting GRAPH .
sorts Path WPath .
subsort Edge < WPath < Path .
op _ _ : Edge Path -> Path .
ops source target : Path -> Node .
op length : Path -> Nat .
var e : Edge .
vars p q r s : Path .
cmb e p : Path if target(e) = source(p) .
ceq (p q) r = p (q r) if target(p) = source(q) /\ target(q) = source(r) .
ceq source(p) = source(e) if e s := p .
ceq target(p) = target(s) if e s := p . 
eq length(e) = 1 .
eq length(e p) = 1 + length(p) .
endfm